#quarkus:
#  http:
#    test-port: 0

# tag::adocSnippet[]
app:
  invoice:
    vatRate: 10
    allowsDiscount: false
    terms: Payment upon receipt
    penalties: Penalty in case of late payment
# end::adocSnippet[]
