version: "3"
services:
    monitoring:
        image: "prom/prometheus"
        container_name: "cdbookstore-monitoring"
        ports:
          - 9090:9090
        volumes:
          - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
