---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: fascicle-deployment
    app.kubernetes.io/version: latest
  name: fascicle-deployment
spec:
  ports:
    - name: http
      nodePort: 30574
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: fascicle-deployment
    app.kubernetes.io/version: latest
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: fascicle-deployment
    app.kubernetes.io/version: latest
  name: fascicle-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fascicle-deployment
      app.kubernetes.io/version: latest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fascicle-deployment
        app.kubernetes.io/version: latest
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: agoncal/hello-fascicle:latest
          imagePullPolicy: IfNotPresent
          name: fascicle-deployment
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
