# tag::adocSnippet[]
openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
paths:
  /authors/{index}:
    get:
      parameters:
      - name: index
        in: path
        description: Author index
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
# end::adocSnippet[]
