# tag::adocSnippet[]
openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
# tag::adocPath[]
paths:
  /authors/{index}:
    get:
      # end::adocPath[]
      parameters:
        - name: index
          in: path
          required: true
          schema:
            format: int32
            type: integer
        - name: index
          in: path
          required: true
          schema:
            format: int32
            type: integer
      responses:
        # tag::adocResponse[]
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
# end::adocResponse[]
# end::adocSnippet[]
