openapi: 3.0.1
info:
  title: Generated API
  version: "1.0"
paths:
  /authors/{index}:
    get:
      parameters:
      - name: index
        in: path
        required: true
        schema:
          format: int32
          type: integer
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
